<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateCountriesTable extends Migration
{
	/**
	 * Run the migrations.
	 *
	 * @return void
	 */
	public function up()
	{
		Schema::create('countries', function (Blueprint $table) {
			$table->increments('id');
			$table->string('name', 50);
			$table->string('iso2', 2);
			$table->string('iso3', 3);
			$table->timestamps();
			$table->index('iso2');
		});

		$countries = [
			['id' => '1','name' => 'Afghanistan','iso2' => 'AF','iso3' => 'AFG'],
			['id' => '2','name' => 'Albania','iso2' => 'AL','iso3' => 'ALB'],
			['id' => '3','name' => 'Algeria','iso2' => 'DZ','iso3' => 'DZA'],
			['id' => '4','name' => 'American Samoa','iso2' => 'AS','iso3' => 'ASM'],
			['id' => '5','name' => 'Andorra','iso2' => 'AD','iso3' => 'AND'],
			['id' => '6','name' => 'Angola','iso2' => 'AO','iso3' => 'AGO'],
			['id' => '7','name' => 'Anguilla','iso2' => 'AI','iso3' => 'AIA'],
			['id' => '8','name' => 'Antarctica','iso2' => 'AQ','iso3' => 'ATA'],
			['id' => '9','name' => 'Antigua and Barbuda','iso2' => 'AG','iso3' => 'ATG'],
			['id' => '10','name' => 'Argentina','iso2' => 'AR','iso3' => 'ARG'],
			['id' => '11','name' => 'Armenia','iso2' => 'AM','iso3' => 'ARM'],
			['id' => '12','name' => 'Aruba','iso2' => 'AW','iso3' => 'ABW'],
			['id' => '13','name' => 'Australia','iso2' => 'AU','iso3' => 'AUS'],
			['id' => '14','name' => 'Austria','iso2' => 'AT','iso3' => 'AUT'],
			['id' => '15','name' => 'Azerbaijan','iso2' => 'AZ','iso3' => 'AZE'],
			['id' => '16','name' => 'Bahamas','iso2' => 'BS','iso3' => 'BHS'],
			['id' => '17','name' => 'Bahrain','iso2' => 'BH','iso3' => 'BHR'],
			['id' => '18','name' => 'Bangladesh','iso2' => 'BD','iso3' => 'BGD'],
			['id' => '19','name' => 'Barbados','iso2' => 'BB','iso3' => 'BRB'],
			['id' => '20','name' => 'Belarus','iso2' => 'BY','iso3' => 'BLR'],
			['id' => '21','name' => 'Belgium','iso2' => 'BE','iso3' => 'BEL'],
			['id' => '22','name' => 'Belize','iso2' => 'BZ','iso3' => 'BLZ'],
			['id' => '23','name' => 'Benin','iso2' => 'BJ','iso3' => 'BEN'],
			['id' => '24','name' => 'Bermuda','iso2' => 'BM','iso3' => 'BMU'],
			['id' => '25','name' => 'Bhutan','iso2' => 'BT','iso3' => 'BTN'],
			['id' => '26','name' => 'Bolivia','iso2' => 'BO','iso3' => 'BOL'],
			['id' => '27','name' => 'Bosnia and Herzegowina','iso2' => 'BA','iso3' => 'BIH'],
			['id' => '28','name' => 'Botswana','iso2' => 'BW','iso3' => 'BWA'],
			['id' => '29','name' => 'Bouvet Island','iso2' => 'BV','iso3' => 'BVT'],
			['id' => '30','name' => 'Brazil','iso2' => 'BR','iso3' => 'BRA'],
			['id' => '31','name' => 'British Indian Ocean Territory','iso2' => 'IO','iso3' => 'IOT'],
			['id' => '32','name' => 'Brunei Darussalam','iso2' => 'BN','iso3' => 'BRN'],
			['id' => '33','name' => 'Bulgaria','iso2' => 'BG','iso3' => 'BGR'],
			['id' => '34','name' => 'Burkina Faso','iso2' => 'BF','iso3' => 'BFA'],
			['id' => '35','name' => 'Burundi','iso2' => 'BI','iso3' => 'BDI'],
			['id' => '36','name' => 'Cambodia','iso2' => 'KH','iso3' => 'KHM'],
			['id' => '37','name' => 'Cameroon','iso2' => 'CM','iso3' => 'CMR'],
			['id' => '38','name' => 'Canada','iso2' => 'CA','iso3' => 'CAN'],
			['id' => '39','name' => 'Cape Verde','iso2' => 'CV','iso3' => 'CPV'],
			['id' => '40','name' => 'Cayman Islands','iso2' => 'KY','iso3' => 'CYM'],
			['id' => '41','name' => 'Central African Republic','iso2' => 'CF','iso3' => 'CAF'],
			['id' => '42','name' => 'Chad','iso2' => 'TD','iso3' => 'TCD'],
			['id' => '43','name' => 'Chile','iso2' => 'CL','iso3' => 'CHL'],
			['id' => '44','name' => 'China','iso2' => 'CN','iso3' => 'CHN'],
			['id' => '45','name' => 'Christmas Island','iso2' => 'CX','iso3' => 'CXR'],
			['id' => '46','name' => 'Cocos (Keeling) Islands','iso2' => 'CC','iso3' => 'CCK'],
			['id' => '47','name' => 'Colombia','iso2' => 'CO','iso3' => 'COL'],
			['id' => '48','name' => 'Comoros','iso2' => 'KM','iso3' => 'COM'],
			['id' => '49','name' => 'Congo','iso2' => 'CG','iso3' => 'COG'],
			['id' => '50','name' => 'Cook Islands','iso2' => 'CK','iso3' => 'COK'],
			['id' => '51','name' => 'Costa Rica','iso2' => 'CR','iso3' => 'CRI'],
			['id' => '52','name' => 'Cote D\'Ivoire','iso2' => 'CI','iso3' => 'CIV'],
			['id' => '53','name' => 'Croatia','iso2' => 'HR','iso3' => 'HRV'],
			['id' => '54','name' => 'Cuba','iso2' => 'CU','iso3' => 'CUB'],
			['id' => '55','name' => 'Cyprus','iso2' => 'CY','iso3' => 'CYP'],
			['id' => '56','name' => 'Czech Republic','iso2' => 'CZ','iso3' => 'CZE'],
			['id' => '57','name' => 'Denmark','iso2' => 'DK','iso3' => 'DNK'],
			['id' => '58','name' => 'Djibouti','iso2' => 'DJ','iso3' => 'DJI'],
			['id' => '59','name' => 'Dominica','iso2' => 'DM','iso3' => 'DMA'],
			['id' => '60','name' => 'Dominican Republic','iso2' => 'DO','iso3' => 'DOM'],
			['id' => '61','name' => 'East Timor','iso2' => 'TP','iso3' => 'TMP'],
			['id' => '62','name' => 'Ecuador','iso2' => 'EC','iso3' => 'ECU'],
			['id' => '63','name' => 'Egypt','iso2' => 'EG','iso3' => 'EGY'],
			['id' => '64','name' => 'El Salvador','iso2' => 'SV','iso3' => 'SLV'],
			['id' => '65','name' => 'Equatorial Guinea','iso2' => 'GQ','iso3' => 'GNQ'],
			['id' => '66','name' => 'Eritrea','iso2' => 'ER','iso3' => 'ERI'],
			['id' => '67','name' => 'Estonia','iso2' => 'EE','iso3' => 'EST'],
			['id' => '68','name' => 'Ethiopia','iso2' => 'ET','iso3' => 'ETH'],
			['id' => '69','name' => 'Falkland Islands (Malvinas)','iso2' => 'FK','iso3' => 'FLK'],
			['id' => '70','name' => 'Faroe Islands','iso2' => 'FO','iso3' => 'FRO'],
			['id' => '71','name' => 'Fiji','iso2' => 'FJ','iso3' => 'FJI'],
			['id' => '72','name' => 'Finland','iso2' => 'FI','iso3' => 'FIN'],
			['id' => '73','name' => 'France','iso2' => 'FR','iso3' => 'FRA'],
			['id' => '74','name' => 'France, Metropolitan','iso2' => 'FX','iso3' => 'FXX'],
			['id' => '75','name' => 'French Guiana','iso2' => 'GF','iso3' => 'GUF'],
			['id' => '76','name' => 'French Polynesia','iso2' => 'PF','iso3' => 'PYF'],
			['id' => '77','name' => 'French Southern Territories','iso2' => 'TF','iso3' => 'ATF'],
			['id' => '78','name' => 'Gabon','iso2' => 'GA','iso3' => 'GAB'],
			['id' => '79','name' => 'Gambia','iso2' => 'GM','iso3' => 'GMB'],
			['id' => '80','name' => 'Georgia','iso2' => 'GE','iso3' => 'GEO'],
			['id' => '81','name' => 'Germany','iso2' => 'DE','iso3' => 'DEU'],
			['id' => '82','name' => 'Ghana','iso2' => 'GH','iso3' => 'GHA'],
			['id' => '83','name' => 'Gibraltar','iso2' => 'GI','iso3' => 'GIB'],
			['id' => '84','name' => 'Greece','iso2' => 'GR','iso3' => 'GRC'],
			['id' => '85','name' => 'Greenland','iso2' => 'GL','iso3' => 'GRL'],
			['id' => '86','name' => 'Grenada','iso2' => 'GD','iso3' => 'GRD'],
			['id' => '87','name' => 'Guadeloupe','iso2' => 'GP','iso3' => 'GLP'],
			['id' => '88','name' => 'Guam','iso2' => 'GU','iso3' => 'GUM'],
			['id' => '89','name' => 'Guatemala','iso2' => 'GT','iso3' => 'GTM'],
			['id' => '90','name' => 'Guinea','iso2' => 'GN','iso3' => 'GIN'],
			['id' => '91','name' => 'Guinea-bissau','iso2' => 'GW','iso3' => 'GNB'],
			['id' => '92','name' => 'Guyana','iso2' => 'GY','iso3' => 'GUY'],
			['id' => '93','name' => 'Haiti','iso2' => 'HT','iso3' => 'HTI'],
			['id' => '94','name' => 'Heard and Mc Donald Islands','iso2' => 'HM','iso3' => 'HMD'],
			['id' => '95','name' => 'Honduras','iso2' => 'HN','iso3' => 'HND'],
			['id' => '96','name' => 'Hong Kong','iso2' => 'HK','iso3' => 'HKG'],
			['id' => '97','name' => 'Hungary','iso2' => 'HU','iso3' => 'HUN'],
			['id' => '98','name' => 'Iceland','iso2' => 'IS','iso3' => 'ISL'],
			['id' => '99','name' => 'India','iso2' => 'IN','iso3' => 'IND'],
			['id' => '100','name' => 'Indonesia','iso2' => 'ID','iso3' => 'IDN'],
			['id' => '101','name' => 'Iran (Islamic Republic of)','iso2' => 'IR','iso3' => 'IRN'],
			['id' => '102','name' => 'Iraq','iso2' => 'IQ','iso3' => 'IRQ'],
			['id' => '103','name' => 'Ireland','iso2' => 'IE','iso3' => 'IRL'],
			['id' => '104','name' => 'Israel','iso2' => 'IL','iso3' => 'ISR'],
			['id' => '105','name' => 'Italy','iso2' => 'IT','iso3' => 'ITA'],
			['id' => '106','name' => 'Jamaica','iso2' => 'JM','iso3' => 'JAM'],
			['id' => '107','name' => 'Japan','iso2' => 'JP','iso3' => 'JPN'],
			['id' => '108','name' => 'Jordan','iso2' => 'JO','iso3' => 'JOR'],
			['id' => '109','name' => 'Kazakhstan','iso2' => 'KZ','iso3' => 'KAZ'],
			['id' => '110','name' => 'Kenya','iso2' => 'KE','iso3' => 'KEN'],
			['id' => '111','name' => 'Kiribati','iso2' => 'KI','iso3' => 'KIR'],
			['id' => '112','name' => 'Korea, Democratic People\'s Republic of','iso2' => 'KP','iso3' => 'PRK'],
			['id' => '113','name' => 'Korea, Republic of','iso2' => 'KR','iso3' => 'KOR'],
			['id' => '114','name' => 'Kuwait','iso2' => 'KW','iso3' => 'KWT'],
			['id' => '115','name' => 'Kyrgyzstan','iso2' => 'KG','iso3' => 'KGZ'],
			['id' => '116','name' => 'Lao People\'s Democratic Republic','iso2' => 'LA','iso3' => 'LAO'],
			['id' => '117','name' => 'Latvia','iso2' => 'LV','iso3' => 'LVA'],
			['id' => '118','name' => 'Lebanon','iso2' => 'LB','iso3' => 'LBN'],
			['id' => '119','name' => 'Lesotho','iso2' => 'LS','iso3' => 'LSO'],
			['id' => '120','name' => 'Liberia','iso2' => 'LR','iso3' => 'LBR'],
			['id' => '121','name' => 'Libyan Arab Jamahiriya','iso2' => 'LY','iso3' => 'LBY'],
			['id' => '122','name' => 'Liechtenstein','iso2' => 'LI','iso3' => 'LIE'],
			['id' => '123','name' => 'Lithuania','iso2' => 'LT','iso3' => 'LTU'],
			['id' => '124','name' => 'Luxembourg','iso2' => 'LU','iso3' => 'LUX'],
			['id' => '125','name' => 'Macau','iso2' => 'MO','iso3' => 'MAC'],
			['id' => '126','name' => 'Macedonia, The Former Yugoslav Republic of','iso2' => 'MK','iso3' => 'MKD'],
			['id' => '127','name' => 'Madagascar','iso2' => 'MG','iso3' => 'MDG'],
			['id' => '128','name' => 'Malawi','iso2' => 'MW','iso3' => 'MWI'],
			['id' => '129','name' => 'Malaysia','iso2' => 'MY','iso3' => 'MYS'],
			['id' => '130','name' => 'Maldives','iso2' => 'MV','iso3' => 'MDV'],
			['id' => '131','name' => 'Mali','iso2' => 'ML','iso3' => 'MLI'],
			['id' => '132','name' => 'Malta','iso2' => 'MT','iso3' => 'MLT'],
			['id' => '133','name' => 'Marshall Islands','iso2' => 'MH','iso3' => 'MHL'],
			['id' => '134','name' => 'Martinique','iso2' => 'MQ','iso3' => 'MTQ'],
			['id' => '135','name' => 'Mauritania','iso2' => 'MR','iso3' => 'MRT'],
			['id' => '136','name' => 'Mauritius','iso2' => 'MU','iso3' => 'MUS'],
			['id' => '137','name' => 'Mayotte','iso2' => 'YT','iso3' => 'MYT'],
			['id' => '138','name' => 'Mexico','iso2' => 'MX','iso3' => 'MEX'],
			['id' => '139','name' => 'Micronesia, Federated States of','iso2' => 'FM','iso3' => 'FSM'],
			['id' => '140','name' => 'Moldova, Republic of','iso2' => 'MD','iso3' => 'MDA'],
			['id' => '141','name' => 'Monaco','iso2' => 'MC','iso3' => 'MCO'],
			['id' => '142','name' => 'Mongolia','iso2' => 'MN','iso3' => 'MNG'],
			['id' => '143','name' => 'Montenegro','iso2' => 'ME','iso3' => 'MNE'],
			['id' => '144','name' => 'Montserrat','iso2' => 'MS','iso3' => 'MSR'],
			['id' => '145','name' => 'Morocco','iso2' => 'MA','iso3' => 'MAR'],
			['id' => '146','name' => 'Mozambique','iso2' => 'MZ','iso3' => 'MOZ'],
			['id' => '147','name' => 'Myanmar','iso2' => 'MM','iso3' => 'MMR'],
			['id' => '148','name' => 'Namibia','iso2' => 'NA','iso3' => 'NAM'],
			['id' => '149','name' => 'Nauru','iso2' => 'NR','iso3' => 'NRU'],
			['id' => '150','name' => 'Nepal','iso2' => 'NP','iso3' => 'NPL'],
			['id' => '151','name' => 'Netherlands','iso2' => 'NL','iso3' => 'NLD'],
			['id' => '152','name' => 'Netherlands Antilles','iso2' => 'AN','iso3' => 'ANT'],
			['id' => '153','name' => 'New Caledonia','iso2' => 'NC','iso3' => 'NCL'],
			['id' => '154','name' => 'New Zealand','iso2' => 'NZ','iso3' => 'NZL'],
			['id' => '155','name' => 'Nicaragua','iso2' => 'NI','iso3' => 'NIC'],
			['id' => '156','name' => 'Niger','iso2' => 'NE','iso3' => 'NER'],
			['id' => '157','name' => 'Nigeria','iso2' => 'NG','iso3' => 'NGA'],
			['id' => '158','name' => 'Niue','iso2' => 'NU','iso3' => 'NIU'],
			['id' => '159','name' => 'Norfolk Island','iso2' => 'NF','iso3' => 'NFK'],
			['id' => '160','name' => 'Northern Mariana Islands','iso2' => 'MP','iso3' => 'MNP'],
			['id' => '161','name' => 'Norway','iso2' => 'NO','iso3' => 'NOR'],
			['id' => '162','name' => 'Oman','iso2' => 'OM','iso3' => 'OMN'],
			['id' => '163','name' => 'Pakistan','iso2' => 'PK','iso3' => 'PAK'],
			['id' => '164','name' => 'Palau','iso2' => 'PW','iso3' => 'PLW'],
			['id' => '165','name' => 'Panama','iso2' => 'PA','iso3' => 'PAN'],
			['id' => '166','name' => 'Papua New Guinea','iso2' => 'PG','iso3' => 'PNG'],
			['id' => '167','name' => 'Paraguay','iso2' => 'PY','iso3' => 'PRY'],
			['id' => '168','name' => 'Peru','iso2' => 'PE','iso3' => 'PER'],
			['id' => '169','name' => 'Philippines','iso2' => 'PH','iso3' => 'PHL'],
			['id' => '170','name' => 'Pitcairn','iso2' => 'PN','iso3' => 'PCN'],
			['id' => '171','name' => 'Poland','iso2' => 'PL','iso3' => 'POL'],
			['id' => '172','name' => 'Portugal','iso2' => 'PT','iso3' => 'PRT'],
			['id' => '173','name' => 'Puerto Rico','iso2' => 'PR','iso3' => 'PRI'],
			['id' => '174','name' => 'Qatar','iso2' => 'QA','iso3' => 'QAT'],
			['id' => '175','name' => 'Reunion','iso2' => 'RE','iso3' => 'REU'],
			['id' => '176','name' => 'Romania','iso2' => 'RO','iso3' => 'ROM'],
			['id' => '177','name' => 'Russian Federation','iso2' => 'RU','iso3' => 'RUS'],
			['id' => '178','name' => 'Rwanda','iso2' => 'RW','iso3' => 'RWA'],
			['id' => '179','name' => 'Saint Kitts and Nevis','iso2' => 'KN','iso3' => 'KNA'],
			['id' => '180','name' => 'Saint Lucia','iso2' => 'LC','iso3' => 'LCA'],
			['id' => '181','name' => 'Saint Vincent and the Grenadines','iso2' => 'VC','iso3' => 'VCT'],
			['id' => '182','name' => 'Samoa','iso2' => 'WS','iso3' => 'WSM'],
			['id' => '183','name' => 'San Marino','iso2' => 'SM','iso3' => 'SMR'],
			['id' => '184','name' => 'Sao Tome and Principe','iso2' => 'ST','iso3' => 'STP'],
			['id' => '185','name' => 'Saudi Arabia','iso2' => 'SA','iso3' => 'SAU'],
			['id' => '186','name' => 'Senegal','iso2' => 'SN','iso3' => 'SEN'],
			['id' => '187','name' => 'Serbia','iso2' => 'RS','iso3' => 'SRB'],
			['id' => '188','name' => 'Seychelles','iso2' => 'SC','iso3' => 'SYC'],
			['id' => '189','name' => 'Sierra Leone','iso2' => 'SL','iso3' => 'SLE'],
			['id' => '190','name' => 'Singapore','iso2' => 'SG','iso3' => 'SGP'],
			['id' => '191','name' => 'Slovakia (Slovak Republic)','iso2' => 'SK','iso3' => 'SVK'],
			['id' => '192','name' => 'Slovenia','iso2' => 'SI','iso3' => 'SVN'],
			['id' => '193','name' => 'Solomon Islands','iso2' => 'SB','iso3' => 'SLB'],
			['id' => '194','name' => 'Somalia','iso2' => 'SO','iso3' => 'SOM'],
			['id' => '195','name' => 'South Africa','iso2' => 'ZA','iso3' => 'ZAF'],
			['id' => '196','name' => 'South Georgia and the South Sandwich Islands','iso2' => 'GS','iso3' => 'SGS'],
			['id' => '197','name' => 'Spain','iso2' => 'ES','iso3' => 'ESP'],
			['id' => '198','name' => 'Sri Lanka','iso2' => 'LK','iso3' => 'LKA'],
			['id' => '199','name' => 'St. Helena','iso2' => 'SH','iso3' => 'SHN'],
			['id' => '200','name' => 'St. Pierre and Miquelon','iso2' => 'PM','iso3' => 'SPM'],
			['id' => '201','name' => 'Sudan','iso2' => 'SD','iso3' => 'SDN'],
			['id' => '202','name' => 'Suriname','iso2' => 'SR','iso3' => 'SUR'],
			['id' => '203','name' => 'Svalbard and Jan Mayen Islands','iso2' => 'SJ','iso3' => 'SJM'],
			['id' => '204','name' => 'Swaziland','iso2' => 'SZ','iso3' => 'SWZ'],
			['id' => '205','name' => 'Sweden','iso2' => 'SE','iso3' => 'SWE'],
			['id' => '206','name' => 'Switzerland','iso2' => 'CH','iso3' => 'CHE'],
			['id' => '207','name' => 'Syrian Arab Republic','iso2' => 'SY','iso3' => 'SYR'],
			['id' => '208','name' => 'Taiwan','iso2' => 'TW','iso3' => 'TWN'],
			['id' => '209','name' => 'Tajikistan','iso2' => 'TJ','iso3' => 'TJK'],
			['id' => '210','name' => 'Tanzania, United Republic of','iso2' => 'TZ','iso3' => 'TZA'],
			['id' => '211','name' => 'Thailand','iso2' => 'TH','iso3' => 'THA'],
			['id' => '212','name' => 'Togo','iso2' => 'TG','iso3' => 'TGO'],
			['id' => '213','name' => 'Tokelau','iso2' => 'TK','iso3' => 'TKL'],
			['id' => '214','name' => 'Tonga','iso2' => 'TO','iso3' => 'TON'],
			['id' => '215','name' => 'Trinidad and Tobago','iso2' => 'TT','iso3' => 'TTO'],
			['id' => '216','name' => 'Tunisia','iso2' => 'TN','iso3' => 'TUN'],
			['id' => '217','name' => 'Turkey','iso2' => 'TR','iso3' => 'TUR'],
			['id' => '218','name' => 'Turkmenistan','iso2' => 'TM','iso3' => 'TKM'],
			['id' => '219','name' => 'Turks and Caicos Islands','iso2' => 'TC','iso3' => 'TCA'],
			['id' => '220','name' => 'Tuvalu','iso2' => 'TV','iso3' => 'TUV'],
			['id' => '221','name' => 'Uganda','iso2' => 'UG','iso3' => 'UGA'],
			['id' => '222','name' => 'Ukraine','iso2' => 'UA','iso3' => 'UKR'],
			['id' => '223','name' => 'United Arab Emirates','iso2' => 'AE','iso3' => 'ARE'],
			['id' => '224','name' => 'United Kingdom','iso2' => 'GB','iso3' => 'GBR'],
			['id' => '225','name' => 'United States','iso2' => 'US','iso3' => 'USA'],
			['id' => '226','name' => 'United States Minor Outlying Islands','iso2' => 'UM','iso3' => 'UMI'],
			['id' => '227','name' => 'Uruguay','iso2' => 'UY','iso3' => 'URY'],
			['id' => '228','name' => 'Uzbekistan','iso2' => 'UZ','iso3' => 'UZB'],
			['id' => '229','name' => 'Vanuatu','iso2' => 'VU','iso3' => 'VUT'],
			['id' => '230','name' => 'Vatican City State (Holy See)','iso2' => 'VA','iso3' => 'VAT'],
			['id' => '231','name' => 'Venezuela','iso2' => 'VE','iso3' => 'VEN'],
			['id' => '232','name' => 'Viet Nam','iso2' => 'VN','iso3' => 'VNM'],
			['id' => '233','name' => 'Virgin Islands (British)','iso2' => 'VG','iso3' => 'VGB'],
			['id' => '234','name' => 'Virgin Islands (U.S.)','iso2' => 'VI','iso3' => 'VIR'],
			['id' => '235','name' => 'Wallis and Futuna Islands','iso2' => 'WF','iso3' => 'WLF'],
			['id' => '236','name' => 'Western Sahara','iso2' => 'EH','iso3' => 'ESH'],
			['id' => '237','name' => 'Yemen','iso2' => 'YE','iso3' => 'YEM'],
			['id' => '238','name' => 'Zaire','iso2' => 'ZR','iso3' => 'ZAR'],
			['id' => '239','name' => 'Zambia','iso2' => 'ZM','iso3' => 'ZMB'],
			['id' => '240','name' => 'Zimbabwe','iso2' => 'ZW','iso3' => 'ZWE']
		];

		foreach($countries as $c) {
            $country = new Country();
            $country->fill($c);
            $country->save();
        }
	}


	/**
	 * Reverse the migrations.
	 *
	 * @return void
	 */
	public function down()
	{
		Schema::dropIfExists('countries');
	}
}
