<?php

return [

    // Uncomment the languages that your site supports - or add new ones.
    // These are sorted by the native name, which is the order you might show them in a language selector.
    // Regional languages are sorted by their base language, so "British English" sorts as "English, British"
    'supportedLocales' => [
        //'ace'         => ['code' => 1, 	 'name' => 'Achinese',             'script' => 'Latn', 'native' => 'Aceh', 'regional' => ''],
        //'af'          => ['code' => 2, 	 'name' => 'Afrikaans',            'script' => 'Latn', 'native' => 'Afrikaans', 'regional' => 'af_ZA'],
        //'agq'         => ['code' => 3, 	 'name' => 'Aghem',                'script' => 'Latn', 'native' => 'Aghem', 'regional' => ''],
        //'ak'          => ['code' => 4, 	 'name' => 'Akan',                 'script' => 'Latn', 'native' => 'Akan', 'regional' => 'ak_GH'],
        //'an'          => ['code' => 5, 	 'name' => 'Aragonese',            'script' => 'Latn', 'native' => 'aragonés', 'regional' => 'an_ES'],
        //'cch'         => ['code' => 6, 	 'name' => 'Atsam',                'script' => 'Latn', 'native' => 'Atsam', 'regional' => ''],
        //'gn'          => ['code' => 7, 	 'name' => 'Guaraní',              'script' => 'Latn', 'native' => 'Avañe’ẽ', 'regional' => ''],
        //'ae'          => ['code' => 8, 	 'name' => 'Avestan',              'script' => 'Latn', 'native' => 'avesta', 'regional' => ''],
        //'ay'          => ['code' => 9, 	 'name' => 'Aymara',               'script' => 'Latn', 'native' => 'aymar aru', 'regional' => 'ay_PE'],
        //'az'          => ['code' => 10 , 'name' => 'Azerbaijani (Latin)',    'script' => 'Latn', 'native' => 'azərbaycanca', 'regional' => 'az_AZ'],
        'id'          => ['code' => 11 , 'name' => 'Indonesian',             'script' => 'Latn', 'native' => 'Bahasa Indonesia', 'regional' => 'id_ID'],
        //'ms'          => ['code' => 12 , 'name' => 'Malay',                  'script' => 'Latn', 'native' => 'Bahasa Melayu', 'regional' => 'ms_MY'],
        //'bm'          => ['code' => 13 , 'name' => 'Bambara',                'script' => 'Latn', 'native' => 'bamanakan', 'regional' => ''],
        //'jv'          => ['code' => 14 , 'name' => 'Javanese (Latin)',       'script' => 'Latn', 'native' => 'Basa Jawa', 'regional' => ''],
        //'su'          => ['code' => 15 , 'name' => 'Sundanese',              'script' => 'Latn', 'native' => 'Basa Sunda', 'regional' => ''],
        //'bh'          => ['code' => 16 , 'name' => 'Bihari',                 'script' => 'Latn', 'native' => 'Bihari', 'regional' => ''],
        //'bi'          => ['code' => 17 , 'name' => 'Bislama',                'script' => 'Latn', 'native' => 'Bislama', 'regional' => ''],
        //'nb'          => ['code' => 18 , 'name' => 'Norwegian Bokmål',       'script' => 'Latn', 'native' => 'Bokmål', 'regional' => 'nb_NO'],
        //'bs'          => ['code' => 19 , 'name' => 'Bosnian',                'script' => 'Latn', 'native' => 'bosanski', 'regional' => 'bs_BA'],
        //'br'          => ['code' => 20 , 'name' => 'Breton',                 'script' => 'Latn', 'native' => 'brezhoneg', 'regional' => 'br_FR'],
        //'ca'          => ['code' => 21 , 'name' => 'Catalan',                'script' => 'Latn', 'native' => 'català', 'regional' => 'ca_ES'],
        //'ch'          => ['code' => 22 , 'name' => 'Chamorro',               'script' => 'Latn', 'native' => 'Chamoru', 'regional' => ''],
        //'ny'          => ['code' => 23 , 'name' => 'Chewa',                  'script' => 'Latn', 'native' => 'chiCheŵa', 'regional' => ''],
        //'kde'         => ['code' => 24 , 'name' => 'Makonde',                'script' => 'Latn', 'native' => 'Chimakonde', 'regional' => ''],
        //'sn'          => ['code' => 25 , 'name' => 'Shona',                  'script' => 'Latn', 'native' => 'chiShona', 'regional' => ''],
        //'co'          => ['code' => 26 , 'name' => 'Corsican',               'script' => 'Latn', 'native' => 'corsu', 'regional' => ''],
        //'cy'          => ['code' => 27 , 'name' => 'Welsh',                  'script' => 'Latn', 'native' => 'Cymraeg', 'regional' => 'cy_GB'],
        'da'          => ['code' => 28 , 'name' => 'Danish',                 'script' => 'Latn', 'native' => 'Dansk', 'regional' => 'da_DK'],
        //'se'          => ['code' => 29 , 'name' => 'Northern Sami',          'script' => 'Latn', 'native' => 'davvisámegiella', 'regional' => 'se_NO'],
        'de'          => ['code' => 30 , 'name' => 'German',                 'script' => 'Latn', 'native' => 'Deutsch', 'regional' => 'de_DE'],
        //'luo'         => ['code' => 31 , 'name' => 'Luo',                    'script' => 'Latn', 'native' => 'Dholuo', 'regional' => ''],
        //'nv'          => ['code' => 32 , 'name' => 'Navajo',                 'script' => 'Latn', 'native' => 'Diné bizaad', 'regional' => ''],
        //'dua'         => ['code' => 33 , 'name' => 'Duala',                  'script' => 'Latn', 'native' => 'duálá', 'regional' => ''],
        //'et'          => ['code' => 34 , 'name' => 'Estonian',               'script' => 'Latn', 'native' => 'eesti', 'regional' => 'et_EE'],
        //'na'          => ['code' => 35 , 'name' => 'Nauru',                  'script' => 'Latn', 'native' => 'Ekakairũ Naoero', 'regional' => ''],
        //'guz'         => ['code' => 36 , 'name' => 'Ekegusii',               'script' => 'Latn', 'native' => 'Ekegusii', 'regional' => ''],
        'en'          => ['code' => 37 , 'name' => 'English',                'script' => 'Latn', 'native' => 'English', 'regional' => 'en_GB'],
        //'en-AU'       => ['code' => 38 , 'name' => 'Australian English',     'script' => 'Latn', 'native' => 'Australian English', 'regional' => 'en_AU'],
        //'en-GB'       => ['code' => 39 , 'name' => 'British English',        'script' => 'Latn', 'native' => 'British English', 'regional' => 'en_GB'],
        //'en-US'       => ['code' => 40 , 'name' => 'U.S. English',           'script' => 'Latn', 'native' => 'U.S. English', 'regional' => 'en_US'],
        'es'          => ['code' => 41 , 'name' => 'Spanish',                'script' => 'Latn', 'native' => 'Español', 'regional' => 'es_ES'],
        //'eo'          => ['code' => 42 , 'name' => 'Esperanto',              'script' => 'Latn', 'native' => 'esperanto', 'regional' => ''],
        //'eu'          => ['code' => 43 , 'name' => 'Basque',                 'script' => 'Latn', 'native' => 'euskara', 'regional' => 'eu_ES'],
        //'ewo'         => ['code' => 44 , 'name' => 'Ewondo',                 'script' => 'Latn', 'native' => 'ewondo', 'regional' => ''],
        //'ee'          => ['code' => 45 , 'name' => 'Ewe',                    'script' => 'Latn', 'native' => 'eʋegbe', 'regional' => ''],
        'fil'         => ['code' => 46 , 'name' => 'Filipino',               'script' => 'Latn', 'native' => 'Filipino', 'regional' => 'fil_PH'],
        'fr'          => ['code' => 47 , 'name' => 'French',                 'script' => 'Latn', 'native' => 'Français', 'regional' => 'fr_FR'],
        //'fr-CA'       => ['code' => 48 , 'name' => 'Canadian French',        'script' => 'Latn', 'native' => 'français canadien', 'regional' => 'fr_CA'],
        //'fy'          => ['code' => 49 , 'name' => 'Western Frisian',        'script' => 'Latn', 'native' => 'frysk', 'regional' => 'fy_DE'],
        //'fur'         => ['code' => 50 , 'name' => 'Friulian',               'script' => 'Latn', 'native' => 'furlan', 'regional' => 'fur_IT'],
        //'fo'          => ['code' => 51 , 'name' => 'Faroese',                'script' => 'Latn', 'native' => 'føroyskt', 'regional' => 'fo_FO'],
        //'gaa'         => ['code' => 52 , 'name' => 'Ga',                     'script' => 'Latn', 'native' => 'Ga', 'regional' => ''],
        //'ga'          => ['code' => 53 , 'name' => 'Irish',                  'script' => 'Latn', 'native' => 'Gaeilge', 'regional' => 'ga_IE'],
        //'gv'          => ['code' => 54 , 'name' => 'Manx',                   'script' => 'Latn', 'native' => 'Gaelg', 'regional' => 'gv_GB'],
        //'sm'          => ['code' => 55 , 'name' => 'Samoan',                 'script' => 'Latn', 'native' => 'Gagana fa’a Sāmoa', 'regional' => ''],
        //'gl'          => ['code' => 56 , 'name' => 'Galician',               'script' => 'Latn', 'native' => 'galego', 'regional' => 'gl_ES'],
        //'ki'          => ['code' => 57 , 'name' => 'Kikuyu',                 'script' => 'Latn', 'native' => 'Gikuyu', 'regional' => ''],
        //'gd'          => ['code' => 58 , 'name' => 'Scottish Gaelic',        'script' => 'Latn', 'native' => 'Gàidhlig', 'regional' => 'gd_GB'],
        //'ha'          => ['code' => 59 , 'name' => 'Hausa',                  'script' => 'Latn', 'native' => 'Hausa', 'regional' => 'ha_NG'],
        //'bez'         => ['code' => 60 , 'name' => 'Bena',                   'script' => 'Latn', 'native' => 'Hibena', 'regional' => ''],
        //'ho'          => ['code' => 61 , 'name' => 'Hiri Motu',              'script' => 'Latn', 'native' => 'Hiri Motu', 'regional' => ''],
        //'hr'          => ['code' => 62 , 'name' => 'Croatian',               'script' => 'Latn', 'native' => 'hrvatski', 'regional' => 'hr_HR'],
        //'bem'         => ['code' => 63 , 'name' => 'Bemba',                  'script' => 'Latn', 'native' => 'Ichibemba', 'regional' => 'bem_ZM'],
        //'io'          => ['code' => 64 , 'name' => 'Ido',                    'script' => 'Latn', 'native' => 'Ido', 'regional' => ''],
        //'ig'          => ['code' => 65 , 'name' => 'Igbo',                   'script' => 'Latn', 'native' => 'Igbo', 'regional' => 'ig_NG'],
        //'rn'          => ['code' => 66 , 'name' => 'Rundi',                  'script' => 'Latn', 'native' => 'Ikirundi', 'regional' => ''],
        //'ia'          => ['code' => 67 , 'name' => 'Interlingua',            'script' => 'Latn', 'native' => 'interlingua', 'regional' => 'ia_FR'],
        //'iu-Latn'     => ['code' => 68 , 'name' => 'Inuktitut (Latin)',      'script' => 'Latn', 'native' => 'Inuktitut', 'regional' => 'iu_CA'],
        //'sbp'         => ['code' => 69 , 'name' => 'Sileibi',                'script' => 'Latn', 'native' => 'Ishisangu', 'regional' => ''],
        //'nd'          => ['code' => 70 , 'name' => 'North Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => ''],
        //'nr'          => ['code' => 71 , 'name' => 'South Ndebele',          'script' => 'Latn', 'native' => 'isiNdebele', 'regional' => 'nr_ZA'],
        //'xh'          => ['code' => 72 , 'name' => 'Xhosa',                  'script' => 'Latn', 'native' => 'isiXhosa', 'regional' => 'xh_ZA'],
        //'zu'          => ['code' => 73 , 'name' => 'Zulu',                   'script' => 'Latn', 'native' => 'isiZulu', 'regional' => 'zu_ZA'],
        'it'          => ['code' => 74 , 'name' => 'Italian',                'script' => 'Latn', 'native' => 'Italiano', 'regional' => 'it_IT'],
        //'ik'          => ['code' => 75 , 'name' => 'Inupiaq',                'script' => 'Latn', 'native' => 'Iñupiaq', 'regional' => 'ik_CA'],
        //'dyo'         => ['code' => 76 , 'name' => 'Jola-Fonyi',             'script' => 'Latn', 'native' => 'joola', 'regional' => ''],
        //'kea'         => ['code' => 77 , 'name' => 'Kabuverdianu',           'script' => 'Latn', 'native' => 'kabuverdianu', 'regional' => ''],
        //'kaj'         => ['code' => 78 , 'name' => 'Jju',                    'script' => 'Latn', 'native' => 'Kaje', 'regional' => ''],
        //'mh'          => ['code' => 79 , 'name' => 'Marshallese',            'script' => 'Latn', 'native' => 'Kajin M̧ajeļ', 'regional' => 'mh_MH'],
        //'kl'          => ['code' => 80 , 'name' => 'Kalaallisut',            'script' => 'Latn', 'native' => 'kalaallisut', 'regional' => 'kl_GL'],
        //'kln'         => ['code' => 81 , 'name' => 'Kalenjin',               'script' => 'Latn', 'native' => 'Kalenjin', 'regional' => ''],
        //'kr'          => ['code' => 82 , 'name' => 'Kanuri',                 'script' => 'Latn', 'native' => 'Kanuri', 'regional' => ''],
        //'kcg'         => ['code' => 83 , 'name' => 'Tyap',                   'script' => 'Latn', 'native' => 'Katab', 'regional' => ''],
        //'kw'          => ['code' => 84 , 'name' => 'Cornish',                'script' => 'Latn', 'native' => 'kernewek', 'regional' => 'kw_GB'],
        //'naq'         => ['code' => 85 , 'name' => 'Nama',                   'script' => 'Latn', 'native' => 'Khoekhoegowab', 'regional' => ''],
        //'rof'         => ['code' => 86 , 'name' => 'Rombo',                  'script' => 'Latn', 'native' => 'Kihorombo', 'regional' => ''],
        //'kam'         => ['code' => 87 , 'name' => 'Kamba',                  'script' => 'Latn', 'native' => 'Kikamba', 'regional' => ''],
        //'kg'          => ['code' => 88 , 'name' => 'Kongo',                  'script' => 'Latn', 'native' => 'Kikongo', 'regional' => ''],
        //'jmc'         => ['code' => 89 , 'name' => 'Machame',                'script' => 'Latn', 'native' => 'Kimachame', 'regional' => ''],
        //'rw'          => ['code' => 90 , 'name' => 'Kinyarwanda',            'script' => 'Latn', 'native' => 'Kinyarwanda', 'regional' => 'rw_RW'],
        //'asa'         => ['code' => 91 , 'name' => 'Kipare',                 'script' => 'Latn', 'native' => 'Kipare', 'regional' => ''],
        //'rwk'         => ['code' => 92 , 'name' => 'Rwa',                    'script' => 'Latn', 'native' => 'Kiruwa', 'regional' => ''],
        //'saq'         => ['code' => 93 , 'name' => 'Samburu',                'script' => 'Latn', 'native' => 'Kisampur', 'regional' => ''],
        //'ksb'         => ['code' => 94 , 'name' => 'Shambala',               'script' => 'Latn', 'native' => 'Kishambaa', 'regional' => ''],
        //'swc'         => ['code' => 95 , 'name' => 'Congo Swahili',          'script' => 'Latn', 'native' => 'Kiswahili ya Kongo', 'regional' => ''],
        'sw'          => ['code' => 96 , 'name' => 'Swahili',                'script' => 'Latn', 'native' => 'Kiswahili', 'regional' => 'sw_KE'],
        //'dav'         => ['code' => 97 , 'name' => 'Dawida',                 'script' => 'Latn', 'native' => 'Kitaita', 'regional' => ''],
        //'teo'         => ['code' => 98 , 'name' => 'Teso',                   'script' => 'Latn', 'native' => 'Kiteso', 'regional' => ''],
        //'khq'         => ['code' => 99 , 'name' => 'Koyra Chiini',           'script' => 'Latn', 'native' => 'Koyra ciini', 'regional' => ''],
        //'ses'         => ['code' => 100, 'name' => 'Songhay',                'script' => 'Latn', 'native' => 'Koyraboro senni', 'regional' => ''],
        //'mfe'         => ['code' => 101, 'name' => 'Morisyen',               'script' => 'Latn', 'native' => 'kreol morisien', 'regional' => ''],
        //'ht'          => ['code' => 102, 'name' => 'Haitian',                'script' => 'Latn', 'native' => 'Kreyòl ayisyen', 'regional' => 'ht_HT'],
        //'kj'          => ['code' => 103, 'name' => 'Kuanyama',               'script' => 'Latn', 'native' => 'Kwanyama', 'regional' => ''],
        //'ksh'         => ['code' => 104, 'name' => 'Kölsch',                 'script' => 'Latn', 'native' => 'Kölsch', 'regional' => ''],
        //'ebu'         => ['code' => 105, 'name' => 'Kiembu',                 'script' => 'Latn', 'native' => 'Kĩembu', 'regional' => ''],
        //'mer'         => ['code' => 106, 'name' => 'Kimîîru',                'script' => 'Latn', 'native' => 'Kĩmĩrũ', 'regional' => ''],
        //'lag'         => ['code' => 107, 'name' => 'Langi',                  'script' => 'Latn', 'native' => 'Kɨlaangi', 'regional' => ''],
        //'lah'         => ['code' => 108, 'name' => 'Lahnda',                 'script' => 'Latn', 'native' => 'Lahnda', 'regional' => ''],
        //'la'          => ['code' => 109, 'name' => 'Latin',                  'script' => 'Latn', 'native' => 'latine', 'regional' => ''],
        'lv'          => ['code' => 110, 'name' => 'Latvian',                'script' => 'Latn', 'native' => 'Latviešu', 'regional' => 'lv_LV'],
        //'to'          => ['code' => 111, 'name' => 'Tongan',                 'script' => 'Latn', 'native' => 'lea fakatonga', 'regional' => ''],
        'lt'          => ['code' => 112, 'name' => 'Lithuanian',             'script' => 'Latn', 'native' => 'Lietuvių', 'regional' => 'lt_LT'],
        //'li'          => ['code' => 113, 'name' => 'Limburgish',             'script' => 'Latn', 'native' => 'Limburgs', 'regional' => 'li_BE'],
        //'ln'          => ['code' => 114, 'name' => 'Lingala',                'script' => 'Latn', 'native' => 'lingála', 'regional' => ''],
        //'lg'          => ['code' => 115, 'name' => 'Ganda',                  'script' => 'Latn', 'native' => 'Luganda', 'regional' => 'lg_UG'],
        //'luy'         => ['code' => 116, 'name' => 'Oluluyia',               'script' => 'Latn', 'native' => 'Luluhia', 'regional' => ''],
        //'lb'          => ['code' => 117, 'name' => 'Luxembourgish',          'script' => 'Latn', 'native' => 'Lëtzebuergesch', 'regional' => 'lb_LU'],
        'hu'          => ['code' => 118, 'name' => 'Hungarian',              'script' => 'Latn', 'native' => 'Magyar', 'regional' => 'hu_HU'],
        //'mgh'         => ['code' => 119, 'name' => 'Makhuwa-Meetto',         'script' => 'Latn', 'native' => 'Makua', 'regional' => ''],
        //'mg'          => ['code' => 120, 'name' => 'Malagasy',               'script' => 'Latn', 'native' => 'Malagasy', 'regional' => 'mg_MG'],
        'mt'          => ['code' => 121, 'name' => 'Maltese',                'script' => 'Latn', 'native' => 'Malti', 'regional' => 'mt_MT'],
        //'mtr'         => ['code' => 122, 'name' => 'Mewari',                 'script' => 'Latn', 'native' => 'Mewari', 'regional' => ''],
        //'mua'         => ['code' => 123, 'name' => 'Mundang',                'script' => 'Latn', 'native' => 'Mundang', 'regional' => ''],
        //'mi'          => ['code' => 124, 'name' => 'Māori',                  'script' => 'Latn', 'native' => 'Māori', 'regional' => 'mi_NZ'],
        'nl'          => ['code' => 125, 'name' => 'Dutch',                  'script' => 'Latn', 'native' => 'Nederlands', 'regional' => 'nl_NL'],
        //'nmg'         => ['code' => 126, 'name' => 'Kwasio',                 'script' => 'Latn', 'native' => 'ngumba', 'regional' => ''],
        //'yav'         => ['code' => 127, 'name' => 'Yangben',                'script' => 'Latn', 'native' => 'nuasue', 'regional' => ''],
        //'nn'          => ['code' => 128, 'name' => 'Norwegian Nynorsk',      'script' => 'Latn', 'native' => 'nynorsk', 'regional' => 'nn_NO'],
        //'oc'          => ['code' => 129, 'name' => 'Occitan',                'script' => 'Latn', 'native' => 'occitan', 'regional' => 'oc_FR'],
        //'ang'         => ['code' => 130, 'name' => 'Old English',            'script' => 'Runr', 'native' => 'Old English', 'regional' => ''],
        //'xog'         => ['code' => 131, 'name' => 'Soga',                   'script' => 'Latn', 'native' => 'Olusoga', 'regional' => ''],
        //'om'          => ['code' => 132, 'name' => 'Oromo',                  'script' => 'Latn', 'native' => 'Oromoo', 'regional' => 'om_ET'],
        //'ng'          => ['code' => 133, 'name' => 'Ndonga',                 'script' => 'Latn', 'native' => 'OshiNdonga', 'regional' => ''],
        //'hz'          => ['code' => 134, 'name' => 'Herero',                 'script' => 'Latn', 'native' => 'Otjiherero', 'regional' => ''],
        //'uz-Latn'     => ['code' => 135, 'name' => 'Uzbek (Latin)',          'script' => 'Latn', 'native' => 'oʼzbekcha', 'regional' => 'uz_UZ'],
        //'nds'         => ['code' => 136, 'name' => 'Low German',             'script' => 'Latn', 'native' => 'Plattdüütsch', 'regional' => 'nds_DE'],
        'pl'          => ['code' => 137, 'name' => 'Polish',                 'script' => 'Latn', 'native' => 'Polski', 'regional' => 'pl_PL'],
        'pt'          => ['code' => 138, 'name' => 'Portuguese',             'script' => 'Latn', 'native' => 'Português', 'regional' => 'pt_PT'],
        //'pt-BR'       => ['code' => 139, 'name' => 'Brazilian Portuguese',   'script' => 'Latn', 'native' => 'português do Brasil', 'regional' => 'pt_BR'],
        //'ff'          => ['code' => 140, 'name' => 'Fulah',                  'script' => 'Latn', 'native' => 'Pulaar', 'regional' => 'ff_SN'],
        //'pi'          => ['code' => 141, 'name' => 'Pahari-Potwari',         'script' => 'Latn', 'native' => 'Pāli', 'regional' => ''],
        //'aa'          => ['code' => 142, 'name' => 'Afar',                   'script' => 'Latn', 'native' => 'Qafar', 'regional' => 'aa_ER'],
        //'ty'          => ['code' => 143, 'name' => 'Tahitian',               'script' => 'Latn', 'native' => 'Reo Māohi', 'regional' => ''],
        //'ksf'         => ['code' => 144, 'name' => 'Bafia',                  'script' => 'Latn', 'native' => 'rikpa', 'regional' => ''],
        'ro'          => ['code' => 145, 'name' => 'Romanian',               'script' => 'Latn', 'native' => 'Română', 'regional' => 'ro_RO'],
        //'cgg'         => ['code' => 146, 'name' => 'Chiga',                  'script' => 'Latn', 'native' => 'Rukiga', 'regional' => ''],
        //'rm'          => ['code' => 147, 'name' => 'Romansh',                'script' => 'Latn', 'native' => 'rumantsch', 'regional' => ''],
        //'qu'          => ['code' => 148, 'name' => 'Quechua',                'script' => 'Latn', 'native' => 'Runa Simi', 'regional' => ''],
        //'nyn'         => ['code' => 149, 'name' => 'Nyankole',               'script' => 'Latn', 'native' => 'Runyankore', 'regional' => ''],
        //'ssy'         => ['code' => 150, 'name' => 'Saho',                   'script' => 'Latn', 'native' => 'Saho', 'regional' => ''],
        //'sc'          => ['code' => 151, 'name' => 'Sardinian',              'script' => 'Latn', 'native' => 'sardu', 'regional' => 'sc_IT'],
        //'de-CH'       => ['code' => 152, 'name' => 'Swiss High German',      'script' => 'Latn', 'native' => 'Schweizer Hochdeutsch', 'regional' => 'de_CH'],
        //'gsw'         => ['code' => 153, 'name' => 'Swiss German',           'script' => 'Latn', 'native' => 'Schwiizertüütsch', 'regional' => ''],
        //'trv'         => ['code' => 154, 'name' => 'Taroko',                 'script' => 'Latn', 'native' => 'Seediq', 'regional' => ''],
        //'seh'         => ['code' => 155, 'name' => 'Sena',                   'script' => 'Latn', 'native' => 'sena', 'regional' => ''],
        //'nso'         => ['code' => 156, 'name' => 'Northern Sotho',         'script' => 'Latn', 'native' => 'Sesotho sa Leboa', 'regional' => 'nso_ZA'],
        //'st'          => ['code' => 157, 'name' => 'Southern Sotho',         'script' => 'Latn', 'native' => 'Sesotho', 'regional' => 'st_ZA'],
        //'tn'          => ['code' => 158, 'name' => 'Tswana',                 'script' => 'Latn', 'native' => 'Setswana', 'regional' => 'tn_ZA'],
        'sq'          => ['code' => 159, 'name' => 'Albanian',               'script' => 'Latn', 'native' => 'Shqip', 'regional' => 'sq_AL'],
        //'sid'         => ['code' => 160, 'name' => 'Sidamo',                 'script' => 'Latn', 'native' => 'Sidaamu Afo', 'regional' => 'sid_ET'],
        //'ss'          => ['code' => 161, 'name' => 'Swati',                  'script' => 'Latn', 'native' => 'Siswati', 'regional' => 'ss_ZA'],
        //'sk'          => ['code' => 162, 'name' => 'Slovak',                 'script' => 'Latn', 'native' => 'slovenčina', 'regional' => 'sk_SK'],
        'sl'          => ['code' => 163, 'name' => 'Slovene',                'script' => 'Latn', 'native' => 'Slovenščina', 'regional' => 'sl_SI'],
        //'so'          => ['code' => 164, 'name' => 'Somali',                 'script' => 'Latn', 'native' => 'Soomaali', 'regional' => 'so_SO'],
        //'sr-Latn'     => ['code' => 165, 'name' => 'Serbian (Latin)',        'script' => 'Latn', 'native' => 'Srpski', 'regional' => 'sr_RS'],
        //'sh'          => ['code' => 166, 'name' => 'Serbo-Croatian',         'script' => 'Latn', 'native' => 'srpskohrvatski', 'regional' => ''],
        'fi'          => ['code' => 167, 'name' => 'Finnish',                'script' => 'Latn', 'native' => 'Suomi', 'regional' => 'fi_FI'],
        'sv'          => ['code' => 168, 'name' => 'Swedish',                'script' => 'Latn', 'native' => 'Svenska', 'regional' => 'sv_SE'],
        //'sg'          => ['code' => 169, 'name' => 'Sango',                  'script' => 'Latn', 'native' => 'Sängö', 'regional' => ''],
        //'tl'          => ['code' => 170, 'name' => 'Tagalog',                'script' => 'Latn', 'native' => 'Tagalog', 'regional' => 'tl_PH'],
        //'tzm-Latn'    => ['code' => 171, 'name' => 'Central Atlas Tamazight (Latin)', 'script' => 'Latn', 'native' => 'Tamazight', 'regional' => ''],
        //'kab'         => ['code' => 172, 'name' => 'Kabyle',                 'script' => 'Latn', 'native' => 'Taqbaylit', 'regional' => 'kab_DZ'],
        //'twq'         => ['code' => 173, 'name' => 'Tasawaq',                'script' => 'Latn', 'native' => 'Tasawaq senni', 'regional' => ''],
        //'shi'         => ['code' => 174, 'name' => 'Tachelhit (Latin)',      'script' => 'Latn', 'native' => 'Tashelhit', 'regional' => ''],
        //'nus'         => ['code' => 175, 'name' => 'Nuer',                   'script' => 'Latn', 'native' => 'Thok Nath', 'regional' => ''],
        'vi'          => ['code' => 176, 'name' => 'Vietnamese',             'script' => 'Latn', 'native' => 'Tiếng Việt', 'regional' => 'vi_VN'],
        //'tg-Latn'     => ['code' => 177, 'name' => 'Tajik (Latin)',          'script' => 'Latn', 'native' => 'tojikī', 'regional' => 'tg_TJ'],
        //'lu'          => ['code' => 178, 'name' => 'Luba-Katanga',           'script' => 'Latn', 'native' => 'Tshiluba', 'regional' => 've_ZA'],
        //'ve'          => ['code' => 179, 'name' => 'Venda',                  'script' => 'Latn', 'native' => 'Tshivenḓa', 'regional' => ''],
        //'tw'          => ['code' => 180, 'name' => 'Twi',                    'script' => 'Latn', 'native' => 'Twi', 'regional' => ''],
        'tr'          => ['code' => 181, 'name' => 'Turkish',                'script' => 'Latn', 'native' => 'Türkçe', 'regional' => 'tr_TR'],
        //'ale'         => ['code' => 182, 'name' => 'Aleut',                  'script' => 'Latn', 'native' => 'Unangax tunuu', 'regional' => ''],
        //'ca-valencia' => ['code' => 183, 'name' => 'Valencian',              'script' => 'Latn', 'native' => 'valencià', 'regional' => ''],
        //'vai-Latn'    => ['code' => 184, 'name' => 'Vai (Latin)',            'script' => 'Latn', 'native' => 'Viyamíĩ', 'regional' => ''],
        //'vo'          => ['code' => 185, 'name' => 'Volapük',                'script' => 'Latn', 'native' => 'Volapük', 'regional' => ''],
        //'fj'          => ['code' => 186, 'name' => 'Fijian',                 'script' => 'Latn', 'native' => 'vosa Vakaviti', 'regional' => ''],
        //'wa'          => ['code' => 187, 'name' => 'Walloon',                'script' => 'Latn', 'native' => 'Walon', 'regional' => 'wa_BE'],
        //'wae'         => ['code' => 188, 'name' => 'Walser',                 'script' => 'Latn', 'native' => 'Walser', 'regional' => 'wae_CH'],
        //'wen'         => ['code' => 189, 'name' => 'Sorbian',                'script' => 'Latn', 'native' => 'Wendic', 'regional' => ''],
        //'wo'          => ['code' => 190, 'name' => 'Wolof',                  'script' => 'Latn', 'native' => 'Wolof', 'regional' => 'wo_SN'],
        //'ts'          => ['code' => 191, 'name' => 'Tsonga',                 'script' => 'Latn', 'native' => 'Xitsonga', 'regional' => 'ts_ZA'],
        //'dje'         => ['code' => 192, 'name' => 'Zarma',                  'script' => 'Latn', 'native' => 'Zarmaciine', 'regional' => ''],
        //'yo'          => ['code' => 193, 'name' => 'Yoruba',                 'script' => 'Latn', 'native' => 'Èdè Yorùbá', 'regional' => 'yo_NG'],
        //'de-AT'       => ['code' => 194, 'name' => 'Austrian German',        'script' => 'Latn', 'native' => 'Österreichisches Deutsch', 'regional' => 'de_AT'],
        'is'          => ['code' => 195, 'name' => 'Icelandic',              'script' => 'Latn', 'native' => 'Íslenska', 'regional' => 'is_IS'],
        'cs'          => ['code' => 196, 'name' => 'Czech',                  'script' => 'Latn', 'native' => 'Čeština', 'regional' => 'cs_CZ'],
        //'bas'         => ['code' => 197, 'name' => 'Basa',                   'script' => 'Latn', 'native' => 'Ɓàsàa', 'regional' => ''],
        //'mas'         => ['code' => 198, 'name' => 'Masai',                  'script' => 'Latn', 'native' => 'ɔl-Maa', 'regional' => ''],
        //'haw'         => ['code' => 199, 'name' => 'Hawaiian',               'script' => 'Latn', 'native' => 'ʻŌlelo Hawaiʻi', 'regional' => ''],
        'el'          => ['code' => 200, 'name' => 'Greek',                  'script' => 'Grek', 'native' => 'Ελληνικά', 'regional' => 'el_GR'],
        //'uz'          => ['code' => 201, 'name' => 'Uzbek (Cyrillic)',       'script' => 'Cyrl', 'native' => 'Ўзбек', 'regional' => 'uz_UZ'],
        //'az-Cyrl'     => ['code' => 202, 'name' => 'Azerbaijani (Cyrillic)', 'script' => 'Cyrl', 'native' => 'Азәрбајҹан', 'regional' => 'uz_UZ'],
        //'ab'          => ['code' => 203, 'name' => 'Abkhazian',              'script' => 'Cyrl', 'native' => 'Аҧсуа', 'regional' => ''],
        //'os'          => ['code' => 204, 'name' => 'Ossetic',                'script' => 'Cyrl', 'native' => 'Ирон', 'regional' => 'os_RU'],
        //'ky'          => ['code' => 205, 'name' => 'Kyrgyz',                 'script' => 'Cyrl', 'native' => 'Кыргыз', 'regional' => 'ky_KG'],
        //'sr'          => ['code' => 206, 'name' => 'Serbian (Cyrillic)',     'script' => 'Cyrl', 'native' => 'Српски', 'regional' => 'sr_RS'],
        //'av'          => ['code' => 207, 'name' => 'Avaric',                 'script' => 'Cyrl', 'native' => 'авар мацӀ', 'regional' => ''],
        //'ady'         => ['code' => 208, 'name' => 'Adyghe',                 'script' => 'Cyrl', 'native' => 'адыгэбзэ', 'regional' => ''],
        //'ba'          => ['code' => 209, 'name' => 'Bashkir',                'script' => 'Cyrl', 'native' => 'башҡорт теле', 'regional' => ''],
        //'be'          => ['code' => 210, 'name' => 'Belarusian',             'script' => 'Cyrl', 'native' => 'беларуская', 'regional' => 'be_BY'],
        'bg'          => ['code' => 211, 'name' => 'Bulgarian',              'script' => 'Cyrl', 'native' => 'Български', 'regional' => 'bg_BG'],
        //'kv'          => ['code' => 212, 'name' => 'Komi',                   'script' => 'Cyrl', 'native' => 'коми кыв', 'regional' => ''],
        'mk'          => ['code' => 213, 'name' => 'Macedonian',             'script' => 'Cyrl', 'native' => 'Македонски', 'regional' => 'mk_MK'],
        //'mn'          => ['code' => 214, 'name' => 'Mongolian (Cyrillic)',   'script' => 'Cyrl', 'native' => 'монгол', 'regional' => 'mn_MN'],
        //'ce'          => ['code' => 215, 'name' => 'Chechen',                'script' => 'Cyrl', 'native' => 'нохчийн мотт', 'regional' => 'ce_RU'],
        'ru'          => ['code' => 216, 'name' => 'Russian',                'script' => 'Cyrl', 'native' => 'Русский', 'regional' => 'ru_RU'],
        //'sah'         => ['code' => 217, 'name' => 'Yakut',                  'script' => 'Cyrl', 'native' => 'саха тыла', 'regional' => ''],
        //'tt'          => ['code' => 218, 'name' => 'Tatar',                  'script' => 'Cyrl', 'native' => 'татар теле', 'regional' => 'tt_RU'],
        //'tg'          => ['code' => 219, 'name' => 'Tajik (Cyrillic)',       'script' => 'Cyrl', 'native' => 'тоҷикӣ', 'regional' => 'tg_TJ'],
        //'tk'          => ['code' => 220, 'name' => 'Turkmen',                'script' => 'Cyrl', 'native' => 'түркменче', 'regional' => 'tk_TM'],
        'ua'          => ['code' => 221, 'name' => 'Ukrainian',              'script' => 'Cyrl', 'native' => 'Українська', 'regional' => 'uk_UA'],
        //'cv'          => ['code' => 222, 'name' => 'Chuvash',                'script' => 'Cyrl', 'native' => 'чӑваш чӗлхи', 'regional' => 'cv_RU'],
        //'cu'          => ['code' => 223, 'name' => 'Church Slavic',          'script' => 'Cyrl', 'native' => 'ѩзыкъ словѣньскъ', 'regional' => ''],
        //'kk'          => ['code' => 224, 'name' => 'Kazakh',                 'script' => 'Cyrl', 'native' => 'қазақ тілі', 'regional' => 'kk_KZ'],
        //'hy'          => ['code' => 225, 'name' => 'Armenian',               'script' => 'Armn', 'native' => 'Հայերեն', 'regional' => 'hy_AM'],
        //'yi'          => ['code' => 226, 'name' => 'Yiddish',                'script' => 'Hebr', 'native' => 'ייִדיש', 'regional' => 'yi_US'],
        'he'          => ['code' => 227, 'name' => 'Hebrew',                 'script' => 'Hebr', 'native' => 'עברית', 'regional' => 'he_IL'],
        //'ug'          => ['code' => 228, 'name' => 'Uyghur',                 'script' => 'Arab', 'native' => 'ئۇيغۇرچە', 'regional' => 'ug_CN'],
        'ur'          => ['code' => 229, 'name' => 'Urdu',                   'script' => 'Arab', 'native' => 'اردو', 'regional' => 'ur_PK'],
        'ar'          => ['code' => 230, 'name' => 'Arabic',                 'script' => 'Arab', 'native' => 'العربية', 'regional' => 'ar_AE'],
        //'uz-Arab'     => ['code' => 231, 'name' => 'Uzbek (Arabic)',         'script' => 'Arab', 'native' => 'اۉزبېک', 'regional' => ''],
        //'tg-Arab'     => ['code' => 232, 'name' => 'Tajik (Arabic)',         'script' => 'Arab', 'native' => 'تاجیکی', 'regional' => 'tg_TJ'],
        //'sd'          => ['code' => 233, 'name' => 'Sindhi',                 'script' => 'Arab', 'native' => 'سنڌي', 'regional' => 'sd_IN'],
        //'fa'          => ['code' => 234, 'name' => 'Persian',                'script' => 'Arab', 'native' => 'فارسی', 'regional' => 'fa_IR'],
        //'pa-Arab'     => ['code' => 235, 'name' => 'Punjabi (Arabic)',       'script' => 'Arab', 'native' => 'پنجاب', 'regional' => 'pa_IN'],
        //'ps'          => ['code' => 236, 'name' => 'Pashto',                 'script' => 'Arab', 'native' => 'پښتو', 'regional' => 'ps_AF'],
        //'ks'          => ['code' => 237, 'name' => 'Kashmiri (Arabic)',      'script' => 'Arab', 'native' => 'کأشُر', 'regional' => 'ks_IN'],
        //'ku'          => ['code' => 238, 'name' => 'Kurdish',                'script' => 'Arab', 'native' => 'کوردی', 'regional' => 'ku_TR'],
        //'dv'          => ['code' => 239, 'name' => 'Divehi',                 'script' => 'Thaa', 'native' => 'ދިވެހިބަސް', 'regional' => 'dv_MV'],
        //'ks-Deva'     => ['code' => 240, 'name' => 'Kashmiri (Devaganari)',  'script' => 'Deva', 'native' => 'कॉशुर', 'regional' => 'ks_IN'],
        //'kok'         => ['code' => 241, 'name' => 'Konkani',                'script' => 'Deva', 'native' => 'कोंकणी', 'regional' => 'kok_IN'],
        //'doi'         => ['code' => 242, 'name' => 'Dogri',                  'script' => 'Deva', 'native' => 'डोगरी', 'regional' => 'doi_IN'],
        //'ne'          => ['code' => 243, 'name' => 'Nepali',                 'script' => 'Deva', 'native' => 'नेपाली', 'regional' => ''],
        //'pra'         => ['code' => 244, 'name' => 'Prakrit',                'script' => 'Deva', 'native' => 'प्राकृत', 'regional' => ''],
        //'brx'         => ['code' => 245, 'name' => 'Bodo',                   'script' => 'Deva', 'native' => 'बड़ो', 'regional' => 'brx_IN'],
        //'bra'         => ['code' => 246, 'name' => 'Braj',                   'script' => 'Deva', 'native' => 'ब्रज भाषा', 'regional' => ''],
        //'mr'          => ['code' => 247, 'name' => 'Marathi',                'script' => 'Deva', 'native' => 'मराठी', 'regional' => 'mr_IN'],
        //'mai'         => ['code' => 248, 'name' => 'Maithili',               'script' => 'Tirh', 'native' => 'मैथिली', 'regional' => 'mai_IN'],
        //'raj'         => ['code' => 249, 'name' => 'Rajasthani',             'script' => 'Deva', 'native' => 'राजस्थानी', 'regional' => ''],
        //'sa'          => ['code' => 250, 'name' => 'Sanskrit',               'script' => 'Deva', 'native' => 'संस्कृतम्', 'regional' => 'sa_IN'],
        'hi'          => ['code' => 251, 'name' => 'Hindi',                  'script' => 'Deva', 'native' => 'हिन्दी', 'regional' => 'hi_IN'],
        //'as'          => ['code' => 252, 'name' => 'Assamese',               'script' => 'Beng', 'native' => 'অসমীয়া', 'regional' => 'as_IN'],
        //'bn'          => ['code' => 253, 'name' => 'Bengali',                'script' => 'Beng', 'native' => 'বাংলা', 'regional' => 'bn_BD'],
        //'mni'         => ['code' => 254, 'name' => 'Manipuri',               'script' => 'Beng', 'native' => 'মৈতৈ', 'regional' => 'mni_IN'],
        //'pa'          => ['code' => 255, 'name' => 'Punjabi (Gurmukhi)',     'script' => 'Guru', 'native' => 'ਪੰਜਾਬੀ', 'regional' => 'pa_IN'],
        //'gu'          => ['code' => 256, 'name' => 'Gujarati',               'script' => 'Gujr', 'native' => 'ગુજરાતી', 'regional' => 'gu_IN'],
        //'or'          => ['code' => 257, 'name' => 'Oriya',                  'script' => 'Orya', 'native' => 'ଓଡ଼ିଆ', 'regional' => 'or_IN'],
        //'ta'          => ['code' => 258, 'name' => 'Tamil',                  'script' => 'Taml', 'native' => 'தமிழ்', 'regional' => 'ta_IN'],
        //'te'          => ['code' => 259, 'name' => 'Telugu',                 'script' => 'Telu', 'native' => 'తెలుగు', 'regional' => 'te_IN'],
        //'kn'          => ['code' => 260, 'name' => 'Kannada',                'script' => 'Knda', 'native' => 'ಕನ್ನಡ', 'regional' => 'kn_IN'],
        //'ml'          => ['code' => 261, 'name' => 'Malayalam',              'script' => 'Mlym', 'native' => 'മലയാളം', 'regional' => 'ml_IN'],
        //'si'          => ['code' => 262, 'name' => 'Sinhala',                'script' => 'Sinh', 'native' => 'සිංහල', 'regional' => 'si_LK'],
        'th'          => ['code' => 263, 'name' => 'Thai',                   'script' => 'Thai', 'native' => 'ไทย', 'regional' => 'th_TH'],
        //'lo'          => ['code' => 264, 'name' => 'Lao',                    'script' => 'Laoo', 'native' => 'ລາວ', 'regional' => 'lo_LA'],
        //'bo'          => ['code' => 265, 'name' => 'Tibetan',                'script' => 'Tibt', 'native' => 'པོད་སྐད་', 'regional' => 'bo_IN'],
        //'dz'          => ['code' => 266, 'name' => 'Dzongkha',               'script' => 'Tibt', 'native' => 'རྫོང་ཁ', 'regional' => 'dz_BT'],
        //'my'          => ['code' => 267, 'name' => 'Burmese',                'script' => 'Mymr', 'native' => 'မြန်မာဘာသာ', 'regional' => 'my_MM'],
        //'ka'          => ['code' => 268, 'name' => 'Georgian',               'script' => 'Geor', 'native' => 'ქართული', 'regional' => 'ka_GE'],
        //'byn'         => ['code' => 269, 'name' => 'Blin',                   'script' => 'Ethi', 'native' => 'ብሊን', 'regional' => 'byn_ER'],
        //'tig'         => ['code' => 270, 'name' => 'Tigre',                  'script' => 'Ethi', 'native' => 'ትግረ', 'regional' => 'tig_ER'],
        //'ti'          => ['code' => 271, 'name' => 'Tigrinya',               'script' => 'Ethi', 'native' => 'ትግርኛ', 'regional' => 'ti_ET'],
        //'am'          => ['code' => 272, 'name' => 'Amharic',                'script' => 'Ethi', 'native' => 'አማርኛ', 'regional' => 'am_ET'],
        //'wal'         => ['code' => 273, 'name' => 'Wolaytta',               'script' => 'Ethi', 'native' => 'ወላይታቱ', 'regional' => 'wal_ET'],
        //'chr'         => ['code' => 274, 'name' => 'Cherokee',               'script' => 'Cher', 'native' => 'ᏣᎳᎩ', 'regional' => ''],
        //'iu'          => ['code' => 275, 'name' => 'Inuktitut (Canadian Aboriginal Syllabics)', 'script' => 'Cans', 'native' => 'ᐃᓄᒃᑎᑐᑦ', 'regional' => 'iu_CA'],
        //'oj'          => ['code' => 276, 'name' => 'Ojibwa',                 'script' => 'Cans', 'native' => 'ᐊᓂᔑᓈᐯᒧᐎᓐ', 'regional' => ''],
        //'cr'          => ['code' => 277, 'name' => 'Cree',                   'script' => 'Cans', 'native' => 'ᓀᐦᐃᔭᐍᐏᐣ', 'regional' => ''],
        //'km'          => ['code' => 278, 'name' => 'Khmer',                  'script' => 'Khmr', 'native' => 'ភាសាខ្មែរ', 'regional' => 'km_KH'],
        //'mn-Mong'     => ['code' => 279, 'name' => 'Mongolian (Mongolian)',  'script' => 'Mong', 'native' => 'ᠮᠣᠨᠭᠭᠣᠯ ᠬᠡᠯᠡ', 'regional' => 'mn_MN'],
        //'shi-Tfng'    => ['code' => 280, 'name' => 'Tachelhit (Tifinagh)',   'script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
        //'tzm'         => ['code' => 281, 'name' => 'Central Atlas Tamazight (Tifinagh)','script' => 'Tfng', 'native' => 'ⵜⴰⵎⴰⵣⵉⵖⵜ', 'regional' => ''],
        //'yue'         => ['code' => 282, 'name' => 'Yue',                    'script' => 'Hant', 'native' => '廣州話', 'regional' => 'yue_HK'],
        'ja'          => ['code' => 283, 'name' => 'Japanese',               'script' => 'Jpan', 'native' => '日本語', 'regional' => 'ja_JP'],
        'cn'          => ['code' => 284, 'name' => 'Chinese (Simplified)',   'script' => 'Hans', 'native' => '简体中文', 'regional' => 'cn_CN'],
        //'zh-Hant'     => ['code' => 285, 'name' => 'Chinese (Traditional)',  'script' => 'Hant', 'native' => '繁體中文', 'regional' => 'zh_CN'],
        //'ii'          => ['code' => 286, 'name' => 'Sichuan Yi',             'script' => 'Yiii', 'native' => 'ꆈꌠꉙ', 'regional' => ''],
        //'vai'         => ['code' => 287, 'name' => 'Vai (Vai)',              'script' => 'Vaii', 'native' => 'ꕙꔤ', 'regional' => ''],
        //'jv-Java'     => ['code' => 288, 'name' => 'Javanese (Javanese)',    'script' => 'Java', 'native' => 'ꦧꦱꦗꦮ', 'regional' => ''],
        'ko'          => ['code' => 289, 'name' => 'Korean',                 'script' => 'Hang', 'native' => '한국어', 'regional' => 'ko_KR'],
        'zsm'          => ['code' => 290, 'name' => 'Malaysian',                 'script' => 'Latn', 'native' => 'Bahasa Malaysia', 'regional' => ''],
    ],

    // Negotiate for the user locale using the Accept-Language header if it's not defined in the URL?
    // If false, system will take app.php locale attribute
    'useAcceptLanguageHeader' => true,
                                    
    // If LaravelLocalizationRedirectFilter is active and hideDefaultLocaleInURL
    // is true, the url would not have the default application language
    //
    // IMPORTANT - When hideDefaultLocaleInURL is set to true, the unlocalized root is treated as the applications default locale "app.locale".
    // Because of this language negotiation using the Accept-Language header will NEVER occur when hideDefaultLocaleInURL is true.
    //
    'hideDefaultLocaleInURL' => false,
                                    
    // If you want to display the locales in particular order in the language selector you should write the order here.
    //CAUTION: Please consider using the appropriate locale code otherwise it will not work
    //Example: 'localesOrder' => ['es','en'],
    'localesOrder' => [],
                                    
];                                  
                                    